### PR TITLE
Add Support for Key within number

### PR DESCRIPTION
**Pull request by chaozhou-seismic**
support JIRA project key like "PB2-1", "pb2-1", "P2P-1", "p2p-1".

my jira project key is "PB2", and jira-lint do not recognize it.

### CODE REVIEW

**Comment by chaozhou-seismic** [comment]
@ravishanker404  how could I pass the PR checks. I have update index.js, but still failed again.

**Comment by rheaditi** [comment]
@chaozhou-seismic I'm getting a diff on your branch when building locally, can you confirm if your versions match these:

```

**Comment by rheaditi** [comment]
I believe it could be due to the node version. @chaozhou-seismic LMK which version you are using & we can debug it further :)

**Comment by chaozhou-seismic** [comment]
thanks, yes, my node version is 12.9, I'll update it and try again.

**Pull request closed without merging**
