### PR TITLE
Add JIRA details to the pull request when the pull request body is un…

### PR DESCRIPTION
**Pull request by Romack**
Currently, if the pull request body is empty, the pull request description
is not decorated with the JIRA ticket details.  This change will update
it such that the details will be added even if the pull request body is
null/undefined.  

It is worth nothing that the value being that is being passed into `getPRDescription` and `shouldUpdatePRDescription` when the action is run is `null` and not `undefined`.  In the tests, I attempted to set the value to null, but the linter complained that the values must either be string or undefined.

Also, incremented the patch version, but don't see that happening in other pull requests so lemme know if I should pull that out.

This pull request addresses the following issue:
https://github.com/ClearTax/jira-lint/issues/48

### CODE REVIEW

**Comment by Romack** [comment]
@all-contributors, please let me know your thoughts on this pr.  Thanks!

**Review by gavin2n — APPROVED** [review]

**Comment by Romack** [comment]
@all-contributors, bump!

**Comment by gavin2n** [comment]
@Romack We merged your pull into our fork, fixed some other bugs here : https://github.com/AmigoLoans/jira-lint

Unfortunately I think this repo is now unmaintained.

**Comment by Romack** [comment]
Closing to get this out of my pull request list

**Pull request closed without merging**
